services:
  postgres:
    image: postgres:13
    restart: always
    container_name: my_container_db
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql_data:/var/lib/mysql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 5050:80
    networks:
      - postgres-network
    depends_on:
      - postgres

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80

networks:
  postgres-network:
    driver: bridge
